name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Trigger on commits to the main branch
  workflow_dispatch:    # Manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker Buildx (optional but recommended for extended build options)
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub using the secrets you configured
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      # Build the Docker image and push it to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vaseem3999/repo1:latest
          




