name: CI/CD to AKS via ACR

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry (ACR)
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker image to ACR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/myapp:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3


      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: set target AKS cluster
        run: |
          az aks get-credentials --resource-group fusion-dev-rg --name fusion-dev-aks
        
      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/k8s.yml -n sample
          